# Generated by Django 5.0.7 on 2024-08-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0003_alter_contactformsubmission_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postformsubmission',
            name='author',
            field=models.CharField(default='author', max_length=20),
        ),
    ]
